### ISSUE TITLE
gameplayer function

### ISSUE THREAD

**Issue by luozijun1984** [maksimhorowitz/nflscrapR#1]
Just want to let you know that after you have changed your -playergame- command to -player_game-, you have not made the change in the -season_player_game- command, which still calls -playergame- instead of -player_game-. Also, the example on github homepage of nflscrapR still demonstrates with playergame and season_playergame commands. Great package, by the way!

**Comment by maksimhorowitz** [comment]
Thanks for the spot, and thank you for the compliment!  More changes coming
soon.

Maksim Horowitz
B.S. Economics and Statistics
Carnegie Mellon University | Class of 2016
347-217-7301 | LinkedIn
<http://www.linkedin.com/profile/view?id=244511864&goback=%2Enmp_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1&trk=spm_pic>

**Comment by maksimhorowitz** [comment]
I also updated it now as well!

Maksim Horowitz
B.S. Economics and Statistics
Carnegie Mellon University | Class of 2016
347-217-7301 | LinkedIn
<http://www.linkedin.com/profile/view?id=244511864&goback=%2Enmp_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1&trk=spm_pic>
