### ISSUE TITLE
Warning when calling season_play_by_play(): number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [maksimhorowitz/nflscrapR#10]
I ran the following code:
pbp_2009 <- season_play_by_play(2009, Weeks = 3)
pbp_2010 <- season_play_by_play(2010, Weeks = 3)
pbp_2011 <- season_play_by_play(2011, Weeks = 3)
pbp_2012 <- season_play_by_play(2012, Weeks = 3)
pbp_2013 <- season_play_by_play(2013, Weeks = 3)
pbp_2014 <- season_play_by_play(2014, Weeks = 3)
pbp_2015 <- season_play_by_play(2015, Weeks = 3)

This ran without errors/warnings for most years, but I did get the following warning for both 2009 and 2012:

Warning message:
In PBP$Rusher[which(PBP$PlayType == "Run")][elidgiblePlays] <- rusherStepfinal :
 number of items to replace is not a multiple of replacement length

This seems to indicate to me that rusherStepfinal really should be the length as the array slice on the left-hand side of the equation, but isn't, which seems like a cause for concern to me. But I could be misunderstanding what's going on. Thanks a lot for any clarity you can give on what's going on here.

**Comment by maksimhorowitz** [comment]
Yes, that is the issue. I will look into it later this week or this weekend!  Thanks for pointing this out.  In the meantime, you can just load the entire season and then subset the first three weeks to create the dataset you desire.

**Comment by MaxPowerWasTaken** [comment]
Hi Maksim, thanks for checking. I'm still getting the same warning though, even after I just re-installed the current master branch from github. 

Code:
```
devtools::install_github(repo = "maksimhorowitz/nflscrapR")
library(nflscrapR)
pbp_data_2009 <- season_play_by_play(2009, 3)

```

Log:

> Downloading GitHub repo maksimhorowitz/nflscrapR@master
> from URL https://api.github.com/repos/maksimhorowitz/nflscrapR/zipball/master
> Installing nflscrapR
> ...
> * installing *source* package 'nflscrapR' ...
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> *** arch - i386
> *** arch - x64
> * DONE (nflscrapR)
> Reloading installed nflscrapR
> 
> > pbp_data_2009 <- season_play_by_play(2009, 3)
> Warning message:
> In PBP$Rusher[which(PBP$PlayType == "Run")][elidgiblePlays] <- rusherStepfinal :
>   number of items to replace is not a multiple of replacement length
>

**Comment by maksimhorowitz** [comment]
Fixed!  Download the latest version.

On Wed, Oct 26, 2016 at 11:38 PM, Maksim Horowitz <maksim.horowitz@gmail.com
> wrote:

> I am getting the same warning, looking into it now.
>
> On Tue, Oct 25, 2016 at 2:49 PM, MaxPowerWasTaken <

**Comment by maksimhorowitz** [comment]
I am getting the same warning, looking into it now.

**Comment by maksimhorowitz** [comment]
Hey,

I'm actually in the middle of fixing this but thanks for the offer! Next
bug I have I definitely will consider your help.

Thanks,

Max

**Comment by maksimhorowitz** [comment]
This should be fixed now!

**Comment by MaxPowerWasTaken** [comment]
Confirmed. The following code no longer throws a warning:

```
devtools::install_github(repo = "maksimhorowitz/nflscrapR")
library(nflscrapR)
#help(season_play_by_play)
pbp_data_2009 <- season_play_by_play(2009, 5)
pbp_data_2012 <- season_play_by_play(2012, 5)

```

Thanks Max!
