### ISSUE TITLE
challenge flags thrown after the two minute warning

### ISSUE THREAD

**Issue by bballmike823** [maksimhorowitz/nflscrapR#107]
The current handling of challenge flags thrown after the two minute warning could be better. Example: play_id 2299 game_id 2018120210
the relevant columns of the table are as follows:
replay_or_challenge 1
replay_or_challenge_result NA
timeout 1
desc Timeout #1 by OAK at 00:07. Raiders charged with a Timeout for throwing the challenge flag under two (2) minutes.

It might make sense to have the replay_or_challenge_result reflect the mistake instead of being NA.

In the future, you might also want to add columns to the table that track the number of challenges that coaches have available.

**Comment by ryurko** [comment]
The latest update labels these challenges as "denied" in the replay_or_challenge_result. Since this is related to [issue 106](https://github.com/maksimhorowitz/nflscrapR/issues/106) I'm closing this issue.
