### ISSUE TITLE
Anyone else having trouble with season_play_by_play()?

### ISSUE THREAD

**Issue by thebamoor** [maksimhorowitz/nflscrapR#11]
My system could be the culprit here so I'm checking with other users. As usual, the latest incarnation of nflscrapR is installed. In fact, that's when the problem started.

Log:

nfl16 <- season_play_by_play(2016,6)
Error in stringr::str_extract_all(unlist(sourceHTML), pattern = "data-gameid=\"[0-9]{10}\"") : 
  lazy-load database '/usr/local/lib/R/3.3/site-library/stringi/R/stringi.rdb' is corrupt
In addition: Warning messages:
1: In stringr::str_extract_all(unlist(sourceHTML), pattern = "data-gameid=\"[0-9]{10}\"") :
  restarting interrupted promise evaluation
2: In stringr::str_extract_all(unlist(sourceHTML), pattern = "data-gameid=\"[0-9]{10}\"") :
  internal error -3 in R_decompress1

**Comment by maksimhorowitz** [comment]
Hey,

Try to see if the Monday night game is downloadable. If not, the system may
be updating. I will look into it as soon as I can.

Max

**Comment by maksimhorowitz** [comment]
Hey this worked for me, did it work for you after trying it again?

**Comment by thebamoor** [comment]
Reinstalled R and it's working fine now. After some research, turned out that installing R with homebrew is problematic, so did the reinstall the plain way.

**Comment by maksimhorowitz** [comment]
Awesome!

**Comment by jrgilbertson** [comment]
Thanks for the great package! Trying to get it up and running but hitting a bizarre error when trying to pull season_play_by_play and game_play_by_play.

`library(nflscrapR)
superbowl47 <- game_play_by_play(GameID = 2013020300)
`

Gives the following error:

`Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('multinom', 'nnet')"`

System info:

`> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nflscrapR_1.4.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     lattice_0.20-34 lubridate_1.6.0 dplyr_0.5.0     assertthat_0.1  bitops_1.0-6    grid_3.3.2      R6_2.2.0        nlme_3.1-128    DBI_0.5-1       magrittr_1.5   
[12] stringi_1.1.2   Matrix_1.2-7.1  RJSONIO_1.3-0   tools_3.3.2     stringr_1.1.0   RCurl_1.95-4.8  mgcv_1.8-16     tibble_1.2     `

**Comment by maksimhorowitz** [comment]
Hey,

This is going to be down until tonight.  Stay posted on this!

Thank you,

Max

**Comment by maksimhorowitz** [comment]
This should now be working!

**Comment by jrgilbertson** [comment]
Back in business! Really appreciate the help.

**Comment by riane1** [comment]
Now I'm having another issue with this!

When I use the function `season_play_by_play(2016)` I am getting this error

> Error in Predict.matrix.tprs.smooth(object, dk$data) : 
>   NA/NaN/Inf in foreign function call (arg 1)

has anyone run into this problem?

**Comment by maksimhorowitz** [comment]
Try downloading the package again, this should be fixed.
