### ISSUE TITLE
Connection errors trying to pull data

### ISSUE THREAD

**Issue by bfurner** [maksimhorowitz/nflscrapR#12]
When I attempt to pull play by play data for any season I am getting the following error:

Error in file(con, "r") : cannot open the connection

The code I am running is as follows:

`playByPlay.2009 <- season_play_by_play(Season = 2009)`

Any help resolving this would be greatly appreciated.

Thanks,

Brian

**Comment by bfurner** [comment]
I have tried a number of different Seasons and Weeks and it seems like I can pull successfully up to and including Weeks = 8, but anything over that yields the connection error.

**Comment by maksimhorowitz** [comment]
Hey Brian,

On Sundays, the API is constantly updating given the games being played.
Thus I think there are connectivity issues. You may have to wait until
after the 4:30 games end today before you can successfully download a full
season! Thanks.

Max

**Comment by bfurner** [comment]
Max,

I waited until all the games were finished and then it worked.  Thanks so much for your efforts.

Best,

Brian
