### ISSUE TITLE
Suggestion:  More Informative Error Message for "Cannot Open the Connection"

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [maksimhorowitz/nflscrapR#13]
I know there's a closed issue where someone asked about the error message below  [here](https://github.com/maksimhorowitz/nflscrapR/issues/12).

> Error in file(con, "r") : cannot open the connection

And I think this has caused some confusion [here](https://github.com/maksimhorowitz/nflscrapR/issues/9) as well, based on bnjcbsn's comment.

I was also pretty confused at one point on this before I found the first issue thread above. I think if  some error-handling code is added to throw a more explanatory error message when the NFL API returns a connection error, there will be less confusion and fewer mis-diagnosed issues among users.

**Comment by maksimhorowitz** [comment]
Hey,

I agree with your error-handling recommendation, I will add this into the
package.

Max

On Mon, Nov 28, 2016 at 12:20 PM, MaxPowerWasTaken <notifications@github.com

**Comment by maksimhorowitz** [comment]
This is fixed now!
