### ISSUE TITLE
Week 9 error: There are no games available for your inputs!

### ISSUE THREAD

**Issue by immenselybored** [maksimhorowitz/nflscrapR#136]
I've been using nflscrapR all season long, but ran into an error this week trying to update.  I'm using the following code
`library(nflscrapR)`
`pbp_add <- scrape_season_play_by_play(2019,type="reg",weeks=9)
`
Using RStudio 1.2.1335
Using R version 3.5.3 (2019-03-11)

**Comment by scottrblock** [comment]
I'm getting the same thing. I'm fairly certain I updated the package correctly because I can get older weeks ok, it's specifically with week 9 of 2019 that there is an issue

**Comment by scottrblock** [comment]
I am able to run `scrape_game_ids(2019)` and get game IDs successfully, so this seems not directly related to https://github.com/maksimhorowitz/nflscrapR/issues/133.

**Comment by scottrblock** [comment]
Hrm, I tried starting over in a new directory, reinstalling everything, and it all worked. @immenselybored you likely need to update the package to get the latest changes.

**Comment by immenselybored** [comment]
I'll give it a shot tomorrow.  Thanks for the quick reply!

**Comment by immenselybored** [comment]
Couldn't wait... decided to try it right now.  I'm getting 
`Warning in install.packages :`
`  package ‘nflscrapR’ is not available (for R version 3.5.3)`
I had this issue when I originally installed it, had to change R versions around a few times.  Is there any chance that a recent update would have affected this?  
More importantly, can you recommend the best version of R to get it to install properly?

**Comment by scottrblock** [comment]
I very much don't know what I'm doing with R (I get the data into python asap), but 3.6.1 seems to work for me

**Comment by crbravens23** [comment]
I ran into an error code few times this past Sunday, Tuesday with attempted updates to 2019 season pbp so I deleted r version from terminal and reinstalled 3.5.1. I then installed all packages needed rlang, tidyverse, dplyr, nflscrapR, etc....... and function worked on first attempt. I get a lot of warning codes that most of packages were built w 3.5.2 but it still worked. Not sure I got lucky or if it will continue to work but 2019 wk 9 seems locked and loaded. I don’t see any problems thus far w quick glance at wk 9 data.

**Comment by immenselybored** [comment]
thanks, i'll give these a try.  @scottrblock I'm a bit of a rookie python programmer.  would love to see any example analyses that you are willing to share

**Comment by sventura** [comment]
Make sure you're re-installing with the following code (i.e. NOT with install.packages()):

`devtools::install_github(repo = "maksimhorowitz/nflscrapR")`

**Comment by immenselybored** [comment]
@sventura you are the H.E.R.O.!!!

**Comment by immenselybored** [comment]
One last note before I close, I had to also remove and reinstall rlang and restart my RStudio session.

Final resolution: remove nflsrapR and use 
`devtools::install_github(repo = "maksimhorowitz/nflscrapR")`
to install

**Comment by immenselybored** [comment]
Premature closure, I still wasn't getting week 9 with R version 3.5.3.

Updated R to 3.6.1 and verified fix.

**Comment by crbravens23** [comment]
Dang it, my update no longer working so I updated to 3.6.1 and reinstalled all packages including nflscrapR and still no wk 9. Help!
