### ISSUE TITLE
Rusher column in play-by-play sometimes wrong

### ISSUE THREAD

**Issue by foggyminded** [maksimhorowitz/nflscrapR#14]
Hi Maksim,

first of all, thanks for your wonderful package!
Unfortunately, I just stumbled upon an issue on the "Rusher" column of the play-by-play dataset when extracting data for the 2015 season.
If the runner has his first name shortened to more than one letter, the value in the "Rusher" column is incorrectly set to the tackler (instead of the real runner in the play).

An example of this can be seen in the second play of the first game of the 2015 season:
```
> pbp <- game_play_by_play(2015091000)
> pbp[2,]$desc
[1] "(15:00) De.Williams right tackle to PIT 38 for 18 yards (D.Hightower)."
> pbp[2,]$Rusher
[1] "D.Hightower"
> pbp[2,]$Tackler1
[1] "D.Hightower"
```

**Comment by foggyminded** [comment]
I attempted to fix this issue by changing the regular expression at line 758 in PlayByPlayBoxScore.R in order to consider first names shortened to 2 or 3 letters (as the following lines seem to already do) in pull request https://github.com/maksimhorowitz/nflscrapR/pull/15.
Hope this helps!

**Comment by maksimhorowitz** [comment]
Hey,

Thanks for pointing this out.  Let me look into your solution.  If it
works, I will use it!

Good catch.

Thanks,

Max

**Comment by foggyminded** [comment]
I'm closing this issue since pull request #18 fixed it.
Thanks for the fix!

**Comment by maksimhorowitz** [comment]
Awesome, thanks to Ron my co-maintainer for getting that done!
