### ISSUE TITLE
Playoffs Score Banner Interfering with scrape_game_ids function

### ISSUE THREAD

**Issue by egibs** [maksimhorowitz/nflscrapR#145]
Reporting for my GitHub-less friend per [his Twitter thread](https://twitter.com/Lunchboxc/status/1216610928893890560).

Banner:
![banner](https://pbs.twimg.com/media/EOJFMMjUwAEyD2G?format=png&name=900x900)

Error (+ code returning 20 IDs):
![code](https://pbs.twimg.com/media/EOJFMMvU4AIL_Ft?format=png&name=900x900)

scrape_game_ids expects 16 games, but the banner seems to be adding 4 additional games resulting in 20 games being returned.

**Comment by heyyouca** [comment]
This is not a fix but running what is attached seems to work to replace scrape_season_play_by_play(2019, type = 'post') as a work around to get 2019 post season data.
[nflscrapR_2019postseason_workaround.txt](https://github.com/maksimhorowitz/nflscrapR/files/4056696/nflscrapR_2019postseason_workaround.txt)
