### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by joncruz120** [maksimhorowitz/nflscrapR#154]
Hi, I'm having trouble installing nflscrapR because one of the dependent packages, namely "hashmap", is not available.

Below is the error message I'm getting from R studio:

Error: Failed to install 'nflscrapR' from GitHub:
  (converted from warning) package ‘hashmap’ is not available (for R version 3.6.3)

Thanks,
Jonathan

**Comment by joncruz120** [comment]
It appears hashmap was removed from the CRAN library. How do I get nflscrap then?

**Comment by sventura** [comment]
Hopefully the authors of hashmap will get it back up soon.

You can try installing an older version of hashmap by downloading the tar.gz here:  https://cran.r-project.org/src/contrib/Archive/hashmap/

You can also try installing hashmap from the author's GitHub:  https://github.com/nathan-russell/hashmap

Once hashmap is installed, you can probably get nflscrapR installed as well.

Haven't tested either potential fix, so let us know if this works and close the issue if so.

**Comment by ryurko** [comment]
The hashmap dependency has been removed, it was unnecessary for this task (and slow actually). Please install nflscrapR again following the README. Thanks for bringing this to our attention!

**Comment by joncruz120** [comment]
Ron, thank you so much. It worked! Thank you again!!
