### ISSUE TITLE
Passer column in play-by-play sometimes empty

### ISSUE THREAD

**Issue by foggyminded** [maksimhorowitz/nflscrapR#16]
Hi Max,

sorry to report another issue I just found out...
It seems to be deeply related to issue https://github.com/maksimhorowitz/nflscrapR/issues/14.
If the passer in a play-by-play row has his first name shortened to more than one letter, the value in the "Passer" column is incorrectly set to "NA".

An example of this can be seen in the second play of the 2016010305 game:
```
> pbp <- game_play_by_play(2016010305)
> pbp[2,]$desc
[1] "(15:00) (Shotgun) Jo.Freeman pass incomplete deep left to T.Hilton."
> pbp[2,]$Passer
[1] NA
```

**Comment by foggyminded** [comment]
I attempted to fix this issue by changing the regular expression at lines 390 and 392 in PlayByPlayBoxScore.R in order to consider first names shortened to 2 letters, as you can see here: https://github.com/foggyminded/nflscrapR/commit/914e660df5fb1a9986ba4817bb7a7daec74c94a1

Hope this helps!

**Comment by maksimhorowitz** [comment]
Appreciate this!  Working on development this week.

**Comment by foggyminded** [comment]
Pull request #18 fixed this issue, so I'm closing it.
Thanks for the fix!

**Comment by maksimhorowitz** [comment]
Thanks again to Ron!
