### ISSUE TITLE
Inaccurate GoalToGo variable

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [maksimhorowitz/nflscrapR#17]
The GoalToGo column is always 1 when the offense is within ten yards of the endzone, and is always 0 otherwise. 

```
pbp_data$yrdline100_factor <- cut(pbp_data$yrdline100, breaks=c(0,10, 100))

table(pbp_data$GoalToGo, pbp_data$yrdline100_factor)
    (0,10] (10,100]
  0      0    43135
  1   2886        0

```

This is not correct.

I highlighted some cases where a team committed an offensive penalty and so was backed up for goal-to-go outside the ten yard line in a [code notebook](https://maxpowerwastaken.github.io/blog/Problem%20with%20nflscrapR%20GoalToGo%20Variable/)

**Comment by maksimhorowitz** [comment]
Thank you, we are looking into this!

**Comment by maksimhorowitz** [comment]
This has been fixed in the most recent merge.  Thank you to my co-collaborator Ron for fixing this.

**Comment by ryurko** [comment]
Thanks Max - and keep letting us know of any errors/issues you find!
