### ISSUE TITLE
Player on incorrect team in game_play_by_play

### ISSUE THREAD

**Issue by pssguy** [maksimhorowitz/nflscrapR#21]
Hi
 Just trying out this great package for first time and attempting to extend some work done [here](http://jessepiburn.com/2017/02/science-of-the-super-bowl/)

For the DEN ATL matchup the ATL running back, D.Freeman, has 3 plays as Rusher with his posteam as DEN on 2016-10-09 when they played Atlanta. They all appear to be related to a shotgun play

**Comment by ryurko** [comment]
Thanks for the catch, looking into it!

**Comment by pssguy** [comment]
Great
Just to clarify, I have only examined one game so it could be more widespread

**Comment by ryurko** [comment]
Issue does not occur with updated scrape_json_play_by_play function
