### ISSUE TITLE
Assign the passer role to the quarterback being sacked

### ISSUE THREAD

**Issue by thebamoor** [maksimhorowitz/nflscrapR#3]
Incredible contribution to our community of football statheads! Just a suggestion for a little tweak: assign the passer role to the quarterback being sacked. Currently, the passer column is blank in plays that ended with a sack. That makes it harder to evaluate passers' overall performance, since it has been shown that sacks are mostly the quarterback's responsibility. Thank you.

**Comment by maksimhorowitz** [comment]
Thank you!  Good idea as I have been trying to figure out how to include
more detail for sack plays.  What are you using the data for?

Maksim Horowitz
B.S. Economics and Statistics
Carnegie Mellon University | Class of 2016
347-217-7301 | LinkedIn
<http://www.linkedin.com/profile/view?id=244511864&goback=%2Enmp_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1&trk=spm_pic>

**Comment by luozijun1984** [comment]
Can this email reach those of you who subscribed?

I think adding qb to passer is redundant. It means exactly the same thing as qb being sacked. And technically no pass has happened. If qb is the passer, who is the intended receiver?

Zijun Luo

**Comment by thebamoor** [comment]
Zijun,

No, it isn't redundant. A play that ended with a sack is a passing play, even if the QB didn't get to pass. A sack is a failed passing play. What's more important is that a sack is more on the QB than the line - when a QB changes a team, he "takes" his sack avoidance ability with him even with a new line, while his old team's year to year correlation of sack rate with a new QB is nil.

Maksim, 

I'm trying to evaluate QBs' play as opposed to team offenses. I'll be more than happy to share my discoveries here.

Here's something I did with your package today - teams' propensity to pass in 2015 after controlling for opponents, downs, yards to go, yardline (curvilinear relationship obviously), time left in the half (also curvilinear), etc. Basically, lower a team ranks, more conservative:

   Call:				
    glm(formula = PassAttempt ~ posteam + DefensiveTeam + as.factor(down) + ydstogo + I(ydstogo^2) + I(ydstogo^3) + yrdline100 + I(yrdline100^2) + I(yrdline100^3) + ScoreDiff + I(ScoreDiff^2) + I(ScoreDiff^3) + I((qtr%%2 == 0) * (3600 - TimeSecs)) + I(((qtr%%2 == 0) * (3600 - TimeSecs))^2) + I(((qtr%%2 == 0) * (3600 - TimeSecs))^3), family = binomial(link = "logit"), data = subset(nfl15, down < 4))				
				
    Deviance Residuals: 				
        Min       1Q   Median       3Q      Max  				
    -2.9192  -1.1206   0.6528   1.0654   2.3138  				
				
    Coefficients:				
    Estimate        Std. Error z value Pr(>|z|)    				
    (Intercept)	-1.56	0.12	-12.73	< 0.0000000000000002
    NE	0.28	0.10	2.88	0.00
    DET	0.07	0.09	0.79	0.43
    PIT	0.05	0.09	0.58	0.56
    NO	0.05	0.10	0.50	0.62
    ARI	0.00 (I added this - they're the reference team)			
    NYG	0.00	0.09	-0.04	0.97
    ATL	-0.04	0.09	-0.39	0.70
    JAC	-0.05	0.10	-0.49	0.62
    BAL	-0.05	0.09	-0.53	0.60
    OAK	-0.05	0.09	-0.56	0.58
    SD	-0.06	0.09	-0.67	0.50
    DEN	-0.06	0.09	-0.70	0.48
    NYJ	-0.11	0.10	-1.18	0.24
    IND	-0.14	0.10	-1.43	0.15
    GB	-0.15	0.09	-1.65	0.10
    WAS	-0.16	0.10	-1.71	0.09
    MIA	-0.17	0.10	-1.67	0.09
    CIN	-0.19	0.09	-2.02	0.04
    PHI	-0.22	0.09	-2.27	0.02
    CAR	-0.27	0.09	-2.85	0.00
    KC	-0.29	0.09	-3.04	0.00
    HOU	-0.29	0.09	-3.04	0.00
    TEN	-0.29	0.10	-2.97	0.00
    CLE	-0.30	0.09	-3.27	0.00
    DAL	-0.35	0.10	-3.60	0.00
    SEA	-0.37	0.09	-4.09	0.00
    TB	-0.39	0.10	-4.14	0.00
    STL	-0.43	0.09	-4.54	0.00
    CHI	-0.50	0.09	-5.40	0.00
    SF	-0.50	0.09	-5.40	0.00
    MIN	-0.52	0.09	-5.56	0.00
    BUF	-0.65	0.10	-6.76	0.00
    Defenses				
    DEN	-0.14	0.09	-1.46	0.15
    TEN	-0.12	0.10	-1.24	0.22
    NE	-0.09	0.10	-0.91	0.36
    MIA	-0.07	0.10	-0.71	0.48
    TB	-0.07	0.10	-0.69	0.49
    GB	-0.06	0.09	-0.63	0.53
    DAL	-0.05	0.10	-0.50	0.62
    SD	-0.04	0.10	-0.41	0.68
    CLE	-0.03	0.09	-0.33	0.74
    CAR	-0.03	0.10	-0.28	0.78
    CHI	-0.02	0.09	-0.19	0.85
    MIN	-0.01	0.09	-0.09	0.93
    ARI	0.00 (reference team)			
    DET	0.01	0.09	0.16	0.88
    BAL	0.02	0.09	0.18	0.85
    PHI	0.02	0.10	0.19	0.85
    SEA	0.03	0.09	0.31	0.76
    IND	0.03	0.10	0.35	0.73
    NO	0.04	0.10	0.37	0.71
    PIT	0.04	0.09	0.41	0.68
    WAS	0.04	0.10	0.40	0.69
    STL	0.04	0.09	0.44	0.66
    KC	0.04	0.10	0.44	0.66
    NYJ	0.05	0.10	0.52	0.60
    JAC	0.06	0.10	0.63	0.53
    SF	0.07	0.09	0.71	0.48
    HOU	0.08	0.10	0.83	0.41
    BUF	0.11	0.10	1.14	0.25
    CIN	0.13	0.09	1.33	0.18
    ATL	0.13	0.10	1.35	0.18
    NYG	0.22	0.10	2.29	0.02
    OAK	0.23	0.09	2.43	0.02
    as.factor(down)2	0.67	0.03	24.33	< 0.0000000000000002
    as.factor(down)3	1.54	0.04	42.71	< 0.0000000000000002
    ydstogo	0.36	0.02	18.10	< 0.0000000000000002
    I(ydstogo^2)	-0.02	0.00	-10.77	< 0.0000000000000002
    I(ydstogo^3)	0.00	0.00	7.59	0.00
    yrdline100	-0.04	0.01	-7.68	0.00
    I(yrdline100^2)	0.00	0.00	8.24	< 0.0000000000000002
    I(yrdline100^3)	0.00	0.00	-8.58	< 0.0000000000000002
    ScoreDiff	-0.04	0.00	-19.38	< 0.0000000000000002
    I(ScoreDiff^2)	0.00	0.00	-4.88	0.00
    I(ScoreDiff^3)	0.00	0.00	2.18	0.03
    I((qtr%%2 == 0) * (3600 - TimeSecs))	0.00	0.00	-2.55	0.01
    I(((qtr%%2 == 0) * (3600 - TimeSecs))^2)	0.00	0.00	5.24	0.00
    I(((qtr%%2 == 0) * (3600 - TimeSecs))^3)	0.00	0.00	-6.19	0.00
    				
    Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1				
				
    (Dispersion parameter for binomial family taken to be 1)				
				
    Null deviance: 48249  on 34996  degrees of freedom				
    Residual deviance: 44717  on 34920  degrees of freedom				
    AIC: 44871				
				
    Number of Fisher Scoring iterations: 4

**Comment by luozijun1984** [comment]
Maksim,

Exactly as you said, sack implies passing, so putting the qb as passer adds no information to the data set. It is the researcher's responsibility to create a variable that is needed. Adding qb to passer works for you, but it won't work the best for other things, such as someone wants to evaluate completion per attempt, yards per attempt, and so on, because in these cases you would need to screen out the play by adding the "no sack" condition. For what is worth, your suggestion would add code to the original program, but then it only benefits when sack matters.

A meaningful way to add more info to "sack" is by analyzing the description or other variables and combine them. For example, where the sacks came from (left, middle, right)? How many yards was the set back? How long the qb held onto the ball? And so on.

Cool analysis though, Maksim.

Zijun Luo

**Comment by maksimhorowitz** [comment]
Zijun,

Thank you for your thorough response and great points!  To clear something
up, I was not the one who responded to your email, rather it was another
subscriber "thebamoor".  These types of dialogues were exactly what I was
hoping would happen when I built this package, so I commend both of you for
being the first engaged users of nflscrapR.

In regards to the suggestion of putting a QB in the Passer column on sack
plays, here is what I am thinking:

I can create a NEW column named "Attempted Passer" or something along those
lines and include the passer on sack attempts in that column.  That would
make it so both of your points would be covered.  I will say, Zijun made
one point I strongly agree with.  This package is meant to provide a
jumping off point for NFL data analysis and obviously, some of a user's
research will require doing some leg work of their own.

thebamoor,

I love the idea of your research!  Send me updates as you go along, and let
me know which functions or data sets you are using most!

Thanks to both of you for the enthusiasm, this makes it feel like all this
hard work was worth it.

Best,

Max

Maksim Horowitz
B.S. Economics and Statistics
Carnegie Mellon University | Class of 2016
347-217-7301 | LinkedIn
<http://www.linkedin.com/profile/view?id=244511864&goback=%2Enmp_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1&trk=spm_pic>

**Comment by luozijun1984** [comment]
Max, I realized I have addressed to the wrong person once I sent it. Unfortunate I am not good at coding R (I work with stata the majority of the time although I use R and Matlab for certain tasks) so I won't be of much help on that end. I will be using your data for at least two projects (will share when I have some results). Maybe you could consider writing some formal documentation for me to cite :)

Zijun Luo

**Comment by thebamoor** [comment]
Maksim,

Your suggestion for a "attempted passer" column would work fine. However, adding the QB to "passer" in sack plays wouldn't prevent users from researching, say, yards per attempt for QBs because all they would have to do is subset the data to PlayType == "Pass". Just saying. I'd be happy with either solution. Once again, I appreciate the work that you do!
