### ISSUE TITLE
2017 play-by-play error

### ISSUE THREAD

**Issue by sansbacon** [maksimhorowitz/nflscrapR#45]
I tried to obtain the data for week 1 of the 2017 season. Received the following error:

pbp_2017 <- season_play_by_play(2017)
Loading required package: XML
Loading required package: RCurl
Loading required package: bitops
Error in nfl.json[[1]]$drives[[x]]$plays : 
  $ operator is invalid for atomic vectors

**Comment by ryurko** [comment]
Do you have the latest version of the package installed?

**Comment by sansbacon** [comment]
I was using your fork. I switched over to the maskimhorowitz version and did not get the error.
