### ISSUE TITLE
Issue Loading pbp data

### ISSUE THREAD

**Issue by dfricci** [maksimhorowitz/nflscrapR#47]
Hi,

I downloaded and loaded the instructions for the package but am still having a hard time loading the data with the season_play_by_play function. For example, when I execute the following code, I get this error:

> pbp_2017 <- season_play_by_play(2017)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.1.1 is already loaded, but >= 0.1.2 is required

Any additional help would be much appreciated.

Thanks!

**Comment by premiumwd** [comment]
any luck on this?

**Comment by maksimhorowitz** [comment]
Try updating the rlang package on your computer!

**Comment by premiumwd** [comment]
How?

**Comment by maksimhorowitz** [comment]
Run the following line of code:

install.packages(‘rlang’)

It will ask you if you want to restart R to update the package and select
“Yes” or “Accept”.
