### ISSUE TITLE
Extra team in 2016?

### ISSUE THREAD

**Issue by Auburngrads** [maksimhorowitz/nflscrapR#48]
This may be an issue with the NFL API but the data contained in the package and the data retrieved using the package for the 2016 season includes 33 teams (not 32).  Seems that data is recorded for the Jacksonville Jaguars as both 'JAC' and 'JAX'.  This only seems to affect the 2016 season. 

    length(unique(nflscrapR::playerstats15$Team)) ## returns 33
    length(unique(nflscrapR::playerstats16$Team)) ## returns 34

This is probably an error caused by how the NFL entered the data, but you may want to update the `playerstats16` dataset.

**Comment by sventura** [comment]
Here's a fix that should clean up the team abbreviations:  

```
    library(tidyverse)
    mutate(data, 
           posteam = case_when(
             posteam == "SD" ~ "LAC",
             posteam == "LA" ~ "LAR",
             posteam == "STL" ~ "LAR",
             posteam == "JAC" ~ "JAX", 
             TRUE ~ posteam
           ))
```

Of course, some users might want to keep the SD and STL abbreviations.
