### ISSUE TITLE
Default Weeks

### ISSUE THREAD

**Issue by gjm112** [maksimhorowitz/nflscrapR#55]
I think weeks should default to 17 instead of 16 in some of these functions so that you get the whole season, not just the first 16 weeks.

**Comment by ryurko** [comment]
Thanks - the functions with the weeks argument need to be overhauled - behind in development compared to the play-by-play functions. Will hopefully get to them soon.

**Comment by ryurko** [comment]
Updated functions scrape_game_ids and scrape_season_play_by_play now fix this issue.
