### ISSUE TITLE
Game scores?

### ISSUE THREAD

**Issue by brikc** [maksimhorowitz/nflscrapR#6]
Hello!

Not really an issue... more of a question. So I apologize in advance if this is not the right forum.

I don't see anywhere that game scores are returned. Am I missing something? Or does this need to be derived from the simple_boxscore data... tds, fgm, etc...

**Comment by maksimhorowitz** [comment]
Hey,

You can merge the score in from the simple_boxscore function.  Where would
you like to see the scores?  Moreso, Which functions would it be useful for
a games score to be outputted? Let me know!

Thanks,

Max

**Comment by brikc** [comment]
I think I must be confused about the structure of the data returned with simple_boxscore... I see a list of data frames that contain the status for rushing, passing, receiving, etc... but I don't see anywhere the final score.  When you say "merge the score in" do you mean sum all the points that are tracked in each of the data frames for rushing, passing, etc?

I think it might be useful to have the scores for first quarter, second quarter, third quarter, final score stored somewhere in the boxscore object but outside of passing, rushing, etc.  I'm pretty sure that data is available from the NFL API.

This package is awesome, by the way! Very cool that you created it and shared it.  :)

**Comment by maksimhorowitz** [comment]
Hey, I also think it is a available, let me look into it!

**Comment by maksimhorowitz** [comment]
Hey,

Sorry for the delay!  If you update the package and use the "season_games" package, you will now find a game score for all games!

Thanks,

Max
