### ISSUE TITLE
Something's wrong with 2017 week 1 data

### ISSUE THREAD

**Issue by cmartin** [maksimhorowitz/nflscrapR#60]
On NFL's website, it says IND vs. LA (rams) finished 9-46, whereas the dataset says LA only scored 44 points.

Here's the code to reproduce : 
```{r}
library(nflscrapR)
library(tidyverse)
pbp <- game_play_by_play(2017091009)
pbp %>% 
select(posteam, PosTeamScore, DefensiveTeam, DefTeamScore,TimeSecs) %>%
arrange(TimeSecs)
```

And the link to the actual Game Center : [http://www.nfl.com/gamecenter/2017091009/2017/REG1/colts@rams](url)

**Comment by ryurko** [comment]
Thanks for the catch but unfortunately the NFL doesn't upload the PATs following return touchdowns (there were two interception returns in this game) to their JSON API which nflscrapR directly accesses. Addressing this is on our list of things to do. It's an annoyance and doesn't make sense why they have this error.

**Comment by cmartin** [comment]
Ok, no problem. That's indeed one weird omission on their part.

**Comment by ryurko** [comment]
Closing this issue since it's outside the scope of what we can address systematically.
