### ISSUE TITLE
How to produce "first down conversion" field?

### ISSUE THREAD

**Issue by rpomponio** [maksimhorowitz/nflscrapR#62]
In the play-by-play, it appears the "FirstDown" field includes plays in which the offense did not convert for a first down. Using the fields already in the dataset (i.e. Touchdown, yds.gained, PenalizedTeam), is it possible to create an indicator variable equal to "1" only when the offense successfully converts and "0" otherwise?

**Comment by ryurko** [comment]
Updated scrape_json_play_by_play function now includes this variable.
