### ISSUE TITLE
season_games Week parameter

### ISSUE THREAD

**Issue by sansbacon** [maksimhorowitz/nflscrapR#69]
The help for v1.4.0 lists a Week parameter for season_games, but the source code does not include this parameter. Is there a script or recommended practice for getting a whole week's worth of data?
![screenshot from 2018-04-21 10-42-03](https://user-images.githubusercontent.com/2755657/39085978-a933a814-4550-11e8-8033-472a9b468a0d.png)
 During the NFL season, that is a common use case. Thanks!

**Comment by sansbacon** [comment]
It could be something like this:

library(XML)

week_player_game <- function(Season, Week, SeasonPhase='REG') {
  url <- 'http://www.nfl.com/ajax/scorestrip?season=%d&seasonType=%s&week=%d'
  data <- xmlParse(sprintf(url, Season, SeasonPhase, Week))
  week_games <- XML:::xmlAttrsToDataFrame(xpathSApply(data, "//g")) 
  playergame.week.unformatted <- lapply(week_games$eid, FUN = player_game)
  suppressWarnings(playergame.week <- dplyr::bind_rows(playergame.week.unformatted)) 
  data.frame(Season = Season, Week = Week, SeasonPhase=SeasonPhase, playergame.week)
}

**Comment by ryurko** [comment]
Updated scrape_game_ids and scrape_season_play_by_play functions allow the user to input a vector of weeks to gather data from.
