### ISSUE TITLE
cannot open the connection - error with season_games function

### ISSUE THREAD

**Issue by bachlaw** [maksimhorowitz/nflscrapR#7]
I can't get around this error:

`Loading required package: XML
Error in file(con, "r") : cannot open the connection`

It happens when trying the following command:
'games.2015 <- season_games(2015)'

It happens with other years too.  All other `season_x` functions work fine though. Has the nfl changed its json format or something?  Would like to merge game data (e.g., stadium, weather, etc.) with play-by-play data, so I'd appreciate any advice or improvements to help with this.

Great job!

Jonathan

**Comment by bachlaw** [comment]
My apologies: figured this out.  This one requires "Season = " explicitly when season is being specified.  Some of the others don't.  That fixed it.  Thanks!

**Comment by nicholassharkey** [comment]
I get the same error but only with 2018. 

```
library(nflscrapR)
season_games2018 <- season_games(Season = 2018)
Error in file(con, "r") : cannot open the connection
```
