### ISSUE TITLE
NFLScrapR not correctly parsing penalties; many "NaN" results in PenaltyType

### ISSUE THREAD

**Issue by jedale** [maksimhorowitz/nflscrapR#70]
Encountered this after scraping all available data and importing into Python via .csv. I happened to be looking at Seahawks 2017 penalties; here is code and results:

penalties = pbp[(pbp.DefensiveTeam == 'SEA') & 
    (pbp['Accepted.Penalty']==1) & 
    (pbp.Season == 2017) &
    (pbp.PenalizedTeam == 'SEA')][['desc', 'PenaltyType']]

penalties

363651 | (13:26) (Shotgun) A.Rodgers pass incomplete sh... | Defensive Pass Interference
(9:37) (Shotgun) A.Rodgers pass short middle i... | NaN
(13:51) (No Huddle, Shotgun) A.Rodgers pass sh... | Defensive Holding
(7:24) J.Vogel punts 57 yards to SEA 35, Cente... | NaN
(13:03) (Shotgun) A.Rodgers pass incomplete de... | Defensive Offside

Seems pretty prevalant; of the Seahawks 79 penalties in 2017 only 42 seem to have been correctly parsed.

**Comment by ryurko** [comment]
Please use the updated functions as this issue has been resolved.
