### ISSUE TITLE
nflteams data frame could use updating

### ISSUE THREAD

**Issue by ronaldjgrafjr** [maksimhorowitz/nflscrapR#74]
For example, the Rams are listed as the St. Louis Rams and the Chargers are still the San Diego Chargers.  Adding a column for season could allows for all teams and abbreviations going as far back as the data can be scraped.

**Comment by sventura** [comment]
Consider merging this with issue [@48](https://github.com/maksimhorowitz/nflscrapR/issues/48)

**Comment by ryurko** [comment]
The nflteams dataset has been updated with the team name changes just to include rows for each used abbreviation, meaning there are still rows for SD and STL. This will just make simpler from looking up the abbreviations from the historical play-by-play data.
