### ISSUE TITLE
Return team not always added in play by play

### ISSUE THREAD

**Issue by bballmike823** [maksimhorowitz/nflscrapR#87]
the line for detecting the return stat does not always catch the return team
dplyr::filter(stringr::str_detect(nfl_stat, "_return") |
                          nfl_stat %in% c("punt_touchback_receiving",
                                          "punt_downed","punt_fair_catch",
                                          "kickoff_fair_catch",
                                          "kickoff_touchback_receiving"))
should be
dplyr::filter(stringr::str_detect(nfl_stat, "_return") |
                        any(nfl_stat** %in% c("punt_touchback_receiving",
                                          "punt_downed","punt_fair_catch",
                                          "kickoff_fair_catch",
                                          "kickoff_touchback_receiving")))

**Comment by ryurko** [comment]
Thanks for the catch, this was due to penalties occurring in addition to the return and has been fixed.
