### ISSUE TITLE
Error in full season data pull

### ISSUE THREAD

**Issue by rsenkpeil** [maksimhorowitz/nflscrapR#89]
When trying to scrape full season data, I get the following error:

Error in if (!(any(stringr::str_detect(play_player_data$nfl_stat, "_td")))) { : 
  missing value where TRUE/FALSE needed

I've tried reinstalling both forks of the package. I noticed that this error isn't thrown for all game id's, just some. I've tried cropping bad game id's but I keep running into more that cause the error. 

I've tried using scrape_season_play_by_play for 2016 and 2017, happens with both. I've also tried scrape_json_play_by_play and looping across game id's for both seasons. Same result. 

Any help/advice would be greatly appreciated! Thanks!

**Comment by ryurko** [comment]
This issue has been corrected. It was due to the occurrence of when the NFL recorded defensive two-point attempts / extra points from turnovers on PATs.
