### ISSUE TITLE
Suggestion: Default Weeks=17 (not 16) in season_play_by_play

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [maksimhorowitz/nflscrapR#9]
Thanks for an awesome library!

One suggestion - There are 17 weeks in an NFL season (16 games and a bye week). So to have season_play_by_play pull the entire season without specifying 'Weeks', default Weeks should be 17 not 16.

**Comment by bnjcbsn** [comment]
Thank you for sharing this package.

There may be another issue here, where the function considers the weeks to be one more than they truly are.
Requesting the current season through week 11 fails. (today is 11/25)

`> library(nflscrapR)
> sg <- season_games(2016, Weeks = 11)
Error in file(con, "r") : cannot open the connection
Called from: file(con, "r")`

While the following succeeds and provides me with week 11 games, except not the Monday Night game:

`library(nflscrapR)
sg <- season_games(2016, Weeks = 10)`

**Comment by MaxPowerWasTaken** [comment]
Hi bnjcbsn,

Based on the package creator's answer [here](https://github.com/maksimhorowitz/nflscrapR/issues/12), my understanding is that 

> cannot open the connection
error is due to the NFL API/data being unavailable for querying sometimes. 

Based on your idea though I tested if I get the same data  from the following two queries:
```
pbp_2015 <- season_play_by_play(2015, Weeks = 17)
pbp_2015_2 <- season_play_by_play(2015)

```

And it turns out they do return exactly the same data (same shape and `all.equal(pbp_2015, pbp_2015_2) ` returns `TRUE`

**Comment by bnjcbsn** [comment]
Please repeat test for current season. Although this is deeper than a default number in current season. 
Please see my fork which resolves current season issues but is not tested for impact to past seasons. 

Ben Jacobson

**Comment by maksimhorowitz** [comment]
Hey,

Thanks for pointing this out everyone.  I am still determining how to set
up the weeks parameter correctly to work across all season and will try to
resolve this problem later in the week.

Ben, thank you for putting together something workable in the meantime.

Max

**Comment by ryurko** [comment]
Closing this old issue, updated scrape_game_ids and scrape_season_play_by_play have a weeks argument allowing the user to enter an arbitrary vector of weeks to return data for.
