### ISSUE TITLE
Incorrect Rusher in season_play_by_play

### ISSUE THREAD

**Issue by bishop22** [maksimhorowitz/nflscrapR#94]
In the 2018 data (all that I've played with, so far), I've found that a single "Rusher" may have many "Rusher_ID"s across different play-by-play records.  In some cases this is due to an incorrect value in the Rusher field.  For example, GameID 2018092307, play_id 3355, has this desc:
"(11:27) C.Ivory right guard to BUF 30 for 4 yards (E.Kendricks, M.Hughes)"
However, the Rusher is K.Cousins.  The Rusher_ID may be correct (other C.Ivory records seem to have 00-0027531 as the Rusher_ID).

**Comment by ryurko** [comment]
Please use the new functions in the README file instead. The original functions are being deprecated and no longer supported for updates.
