### ISSUE TITLE
Yards.Gained not accurate with laterals

### ISSUE THREAD

**Issue by bishop22** [maksimhorowitz/nflscrapR#95]
As an example, for GameID 2018091606 and play_id 4196, Yards.Gained = 7, but statistically it was -5.  Here is the desc:
(:03) (Shotgun) N.Foles pass short right to Z.Ertz to PHI 28 for 7 yards. Lateral to N.Agholor to PHI 21 for -7 yards. Lateral to N.Foles to PHI 15 for -6 yards. Lateral to W.Smallwood to PHI 19 for 4 yards. FUMBLES, RECOVERED by TB-L.David at PHI 16.

In the official NFL stats, N.Foles was given -5 passing yards.  It would be nice to have the ability to match the NFL passing stats for the season, using information in the data frame that is returned.  Of course there will be similar issues with receiving yards, which might be tough to tackle at an individual player level, given an arbitrary number of players could receive a lateral and gain/lose receiving yards.

**Comment by ryurko** [comment]
Thanks for noticing this, but the original game_play_by_play function is no longer supported. Please use the scrape_json_play_by_play and scrape_season_play_by_play instead.

**Comment by bishop22** [comment]
Thanks for the help. I didn't have visibility to those functions' existence
when I installed, but I see the code now.
