### ISSUE TITLE
scrape_json_play_by_play(2018102900) error

### ISSUE THREAD

**Issue by MargareeMan** [maksimhorowitz/nflscrapR#96]
Error in if (!(any(stringr::str_detect(play_player_data$nfl_stat, "_td")))) { : 
  missing value where TRUE/FALSE needed

I downloaded and parsed the drive elements of this json file ("http://www.nfl.com/liveupdate/game-center/2018090600/2018090600_gtd.\json") using Mathematica.  The error message suggests the problem is in a side call to NFL.com player data. 

Also, both nflgame and nfldb update with no error (https://github.com/BurntSushi/nflgame and https://github.com/BurntSushi/nfldb).  An these Python-based apps rely on scraping the NFL.com player profiles. 

I apologize in advance if this is an inappropriate place to note these issues.

**Comment by ryurko** [comment]
Please reinstall the package, this was an issue fixed in one of the latest updates.

**Comment by MargareeMan** [comment]
Thank you the rapid response.  

It is also the case that the latest build (Built: R 3.5.1; ; 2018-10-14 01:39:55 UTC; windows) also adds 4 new columns.  ("defensive_extra_point_attempt", "defensive_extra_point_conv", "defensive_two_point_attempt", "defensive_two_point_conv").

Is there a blog or wiki that keeps users abreast of these sorts of changes?

**Comment by ryurko** [comment]
Currently no but it's something we intend to put together as the package is becoming more popular.
