### ISSUE TITLE
season_play_by_play(): got warnings about "unequal factor levels", "binding character and factor vector, coercing into character vector"

### ISSUE THREAD

**Issue by thebamoor** [maksimhorowitz/nflscrapR#97]
Hi. Your package looks amazing, but for some reason I can't seem to get it working smoothly.

The log is below. All of my packages are updated. AFAIK, I've installed all the dependencies (can't exclude the possibility that I missed some). Those error messages happen when I download other seasons as well. I'd end up with a tibble data frame of the season, with over 45k plays, but find that it doesn't work normally (can divulge details if you think they're important).
 
> pbp_2018 <- season_play_by_play(2018)
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
3: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
4: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
5: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
6: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
7: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
8: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
9: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
10: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
11: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
12: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
13: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
14: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
15: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
16: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
17: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
18: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
19: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
20: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
21: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
22: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
23: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
24: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
25: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
26: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
27: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
28: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
29: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
30: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
31: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
32: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
33: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
34: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
35: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
36: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
37: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
38: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
39: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
40: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
41: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
42: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
43: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
44: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
45: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
46: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
47: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
48: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
49: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
50: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector

**Comment by sventura** [comment]
These are just warning messages, not error messages.  My guess is that these can be safely ignored.

If you have specific details about what's wrong with the resulting data frame, please share.

**Comment by thebamoor** [comment]
That's strange because I installed the package just a few days ago directly from github just a few days. To be sure, I attempted re-installation. Result:

```
> devtools::install_github(repo = "maksimhorowitz/nflscrapR")
Skipping install of 'nflscrapR' from a github remote, the SHA1 (90cd0d94) has not changed since last install.
  Use `force = TRUE` to force installation
```

**Comment by thebamoor** [comment]
Good sirs, so no clue as to what went wrong? Alright, I guess you may as well as close this.

**Comment by ryurko** [comment]
You're using a function that will be deprecated following the completion of the current NFL season. Please use scrape_json_play_by_play() for individual games, or scrape_season_play_by_play() instead. See the README file for more info on the new functions.

**Comment by thebamoor** [comment]
Alright, I'll do that. Thank you.
